//! Schema migrations. The list is generated by `build.rs` from
//! `migrations/*.sql`; to change the schema, add a new file there (never edit
//! an applied one). Applied ids are recorded in `schema_migrations`, and the
//! latest one is mirrored in `meta.schema_version`.

use anyhow::{Context, Result};
use rusqlite::{Connection, OptionalExtension, TransactionBehavior, params};

use crate::clock::{self, Clock, SystemClock};

include!(concat!(env!("OUT_DIR"), "/migrations.rs"));

const BOOTSTRAP: &str = "
CREATE TABLE IF NOT EXISTS meta (
    key   TEXT PRIMARY KEY,
    value TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS schema_migrations (
    id            TEXT PRIMARY KEY,
    applied_at_us INTEGER NOT NULL
);
";

pub(crate) fn migrate(conn: &mut Connection) -> Result<()> {
    // Fast path without the write lock, so readers (the dashboard) never
    // wait on a running ingest just to learn the schema is current.
    if all_applied(conn) {
        return Ok(());
    }
    // IMMEDIATE takes the write lock up front, so two processes opening a
    // fresh database cannot both apply the same migration.
    let tx = conn.transaction_with_behavior(TransactionBehavior::Immediate)?;
    tx.execute_batch(BOOTSTRAP)?;
    for (id, sql) in MIGRATIONS {
        let applied: bool = tx.query_row(
            "SELECT EXISTS(SELECT 1 FROM schema_migrations WHERE id = ?1)",
            [id],
            |row| row.get(0),
        )?;
        if applied {
            continue;
        }
        tx.execute_batch(sql)
            .with_context(|| format!("apply migration {id}"))?;
        tx.execute(
            "INSERT INTO schema_migrations (id, applied_at_us) VALUES (?1, ?2)",
            params![id, clock::to_micros(SystemClock.now())],
        )?;
    }
    if let Some((latest, _)) = MIGRATIONS.last() {
        tx.execute(
            "INSERT INTO meta (key, value) VALUES ('schema_version', ?1)
             ON CONFLICT(key) DO UPDATE SET value = excluded.value",
            [latest],
        )?;
    }
    tx.commit()?;
    Ok(())
}

fn all_applied(conn: &Connection) -> bool {
    let applied: Result<i64, _> =
        conn.query_row("SELECT COUNT(*) FROM schema_migrations", [], |row| {
            row.get(0)
        });
    applied.is_ok_and(|count| count as usize >= MIGRATIONS.len())
}

/// The id of the latest applied migration, if any.
pub fn schema_version(conn: &Connection) -> Result<Option<String>> {
    Ok(conn
        .query_row(
            "SELECT value FROM meta WHERE key = 'schema_version'",
            [],
            |row| row.get(0),
        )
        .optional()?)
}
